Repository PandasWhoCode/governance, pull requests merged in 2025-04, with the labels that each got.

#6 feat: Add initial configure-custom-properties action
  .github/workflows/configure-custom-properties.yaml
  properties_schema.json
Labels: enhancement

#8 chore: Add a cron job to the configure-custom-properties.yaml
  .github/workflows/configure-custom-properties.yaml
Labels: enhancement

#11 chore: add repo files
  .github/SECURITY.md
  .github/workflows/validate-conventional-commits.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: chore

#4 ci: use PWC read-all-custom-properties action to read all properties
  .github/workflows/read-all-custom-properties.yaml
  repo-properties.yaml
Labels: enhancement, ci

#2 ci: add new workflow to update all repos in org custom properties
  .github/workflows/update-custom-properties.yaml
  repo-properties.yaml
Labels: enhancement, ci

#17 ci: update custom properties to commit sha
  .github/workflows/update-custom-properties.yaml
Labels: ci

#19 chore: Move properties_schema.json to .github
  .github/properties_schema.json
  .github/workflows/configure-custom-properties.yaml
Labels: chore
